### ISSUE TITLE
Line by line ES inserts is super slow

### ISSUE THREAD

**Issue by mguillaume** [awslabs/aws-detailed-billing-parser#1]
I have a medium-size AWS account (~75 instances). The detailed monthly billing report is around 750k lines.
I cloned your code about 3 weeks ago (prior to the addition of the check option).
A full month import on my workstation was taking about 10 hours.

I've made some changes to use the streaming_bulk function instead of es.index for each line and the ingest time is down to 7 minutes.
That isn't compatible with what you added for the "check" option though, so I can't do a pull request, but that may be something you'd want to look into given the performance increase.

I'm not running in lambda, so dropping an index and re-ingesting it in 10ish minutes is acceptable for me.
Not quite sure how you could do progressive import though. Are the new lines in the files guaranteed to be appended after the existing ones? In that case you could just save a row index and start from there for the next round. Otherwise... not quite sure.

**Comment by koiker** [comment]
Hi mguillaume,

Thanks for your comments. 
I agree with you that the current es.index is way slow than a bulk operation and I will include a bulk function soon.
At the same time I'm planning to split the work in threads to parallelize the send of lines and utilize more CPU cores when available. (If you look at your code running you will see only one CPU fully utilized).
Some customers has billing files of multiple Gigabytes of size and to run in a single thread will be painfully. :-)

Progressive import necessarily need to check the existence of a record using the field RecordID. The billing file cannot guarantee that already processed lines come first. (Specially consolidated multi-account billing)

But to improve the performance temporarily you can run the parser in a EC2 that is closely to the ES service or even run the billing locally if you are running Elasticsearch in EC2. (Part of the problem is the overhead of each line is a transaction that wait for a return of ES)

 If possible, send your changes to me by e-mail?

Regards,
Rafael Koike

**Comment by koiker** [comment]
Hi Matthieu,

I have included the es bulk function (Improvements up to 400% :-)
Thanks!
