### ISSUE TITLE
Can dbrparser be compatible with ElasticSearch Version 6.x

### ISSUE THREAD

**Issue by aadeshrao** [awslabs/aws-detailed-billing-parser#10]
Hello,

I have been trying to use the dbrparser tool to index billing details into ElasticSearch cluster that has es version 6.x. When I run, I get the following error:

pkg_resources.DistributionNotFound: The 'elasticsearch<3.0.0,>=2.2.0' distribution was not found and is required by awsdbrparser

Is there a possibility to use the dbrparser tool for ElasticSearch version 6.x

Note: I have no errors when I run the dbrparser with the python elasticsearch client 'elasticsearch>=2.0.0,<3.0.0'. I do encounter the error when my elasticsearch client is 'elasticsearch (6.3.1)'

![es](https://user-images.githubusercontent.com/28263416/45367133-2876e000-b5fe-11e8-94cf-2fa9978fa48a.JPG)

Thanks,
Aadesh.K

**Comment by koiker** [comment]
Hi Aadesh.K,

The ElasticSearch 6.x has a shift in the the index, documents and types model that is incompatible with the current implementation.

We are planning to launch a new [Cost Optimization monitor](https://aws.amazon.com/answers/account-management/cost-optimization-monitor/) that will use CUR files instead of DBR files and this will move from a tool running in a EC2 instance to lambda functions triggered when the new CUR file is put in the S3 bucket.
With this in mind we will change the way that we send the data and the way that we structure the documents and types to be in conformity with ElasticSearch 6.x

So, for this tool we don't have plans to add ES 6.x compatibility.

**Comment by aadeshrao** [comment]
Thanks @koiker !
